// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: api/v1/launcher.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LauncherService_Launch_FullMethodName = "/api.LauncherService/Launch"
)

// LauncherServiceClient is the client API for LauncherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LauncherServiceClient interface {
	Launch(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error)
}

type launcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLauncherServiceClient(cc grpc.ClientConnInterface) LauncherServiceClient {
	return &launcherServiceClient{cc}
}

func (c *launcherServiceClient) Launch(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error) {
	out := new(LaunchResponse)
	err := c.cc.Invoke(ctx, LauncherService_Launch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LauncherServiceServer is the server API for LauncherService service.
// All implementations must embed UnimplementedLauncherServiceServer
// for forward compatibility
type LauncherServiceServer interface {
	Launch(context.Context, *LaunchRequest) (*LaunchResponse, error)
	mustEmbedUnimplementedLauncherServiceServer()
}

// UnimplementedLauncherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLauncherServiceServer struct {
}

func (UnimplementedLauncherServiceServer) Launch(context.Context, *LaunchRequest) (*LaunchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Launch not implemented")
}
func (UnimplementedLauncherServiceServer) mustEmbedUnimplementedLauncherServiceServer() {}

// UnsafeLauncherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LauncherServiceServer will
// result in compilation errors.
type UnsafeLauncherServiceServer interface {
	mustEmbedUnimplementedLauncherServiceServer()
}

func RegisterLauncherServiceServer(s grpc.ServiceRegistrar, srv LauncherServiceServer) {
	s.RegisterService(&LauncherService_ServiceDesc, srv)
}

func _LauncherService_Launch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LauncherServiceServer).Launch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LauncherService_Launch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LauncherServiceServer).Launch(ctx, req.(*LaunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LauncherService_ServiceDesc is the grpc.ServiceDesc for LauncherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LauncherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.LauncherService",
	HandlerType: (*LauncherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Launch",
			Handler:    _LauncherService_Launch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/launcher.proto",
}
